import{createServer}from'node:http';import{mkdirSync}from'node:fs';import{DatabaseSync}from'node:sqlite';
mkdirSync('data',{recursive:true});const db=new DatabaseSync('data/ecars-scout.db');db.exec(`PRAGMA journal_mode=WAL;PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS cars(id TEXT PRIMARY KEY,raw_json TEXT NOT NULL,first_seen_at INTEGER NOT NULL,last_checked_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS car_snapshots(id INTEGER PRIMARY KEY,car_id TEXT NOT NULL,snapshot_json TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS feed_items(id INTEGER PRIMARY KEY,car_id TEXT NOT NULL UNIQUE,position INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending');
CREATE TABLE IF NOT EXISTS car_decisions(id INTEGER PRIMARY KEY AUTOINCREMENT,car_id TEXT NOT NULL UNIQUE,decision TEXT NOT NULL,comment TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS attribute_feedback(id INTEGER PRIMARY KEY AUTOINCREMENT,car_id TEXT NOT NULL,attribute_key TEXT NOT NULL,raw_value TEXT,display_value TEXT,sentiment TEXT NOT NULL,context_json TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(car_id,attribute_key));
CREATE TABLE IF NOT EXISTS preference_signals(id INTEGER PRIMARY KEY,key TEXT NOT NULL,value REAL NOT NULL,context_json TEXT,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS preference_hypotheses(id INTEGER PRIMARY KEY,key TEXT UNIQUE NOT NULL,statement TEXT NOT NULL,confidence REAL NOT NULL DEFAULT 0,supporting_count INTEGER NOT NULL DEFAULT 0,contradicting_count INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'unconfirmed',updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS llm_analyses(id INTEGER PRIMARY KEY,analysis_json TEXT,status TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS clarifying_questions(id INTEGER PRIMARY KEY,question TEXT NOT NULL,options_json TEXT NOT NULL,answer TEXT,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS scrape_runs(id INTEGER PRIMARY KEY,status TEXT NOT NULL,started_at INTEGER NOT NULL,finished_at INTEGER,details_json TEXT);
CREATE TABLE IF NOT EXISTS app_settings(key TEXT PRIMARY KEY,value_json TEXT NOT NULL,updated_at INTEGER NOT NULL);`);
const now=Date.now();const seedHypothesis=db.prepare(`INSERT OR IGNORE INTO preference_hypotheses(key,statement,confidence,supporting_count,contradicting_count,status,updated_at) VALUES(?,?,?,?,?,?,?)`);
[
 ['vat_deductible_required','VAT должен быть возвратным (VAT deductible)',1,0,0,'confirmed'],
 ['total_budget_10000','Ориентир полной стоимости в Черногории — около €10 000',.78,0,0,'confirmed'],
 ['diesel_preference','Дизель предпочтителен, но не обязателен',.62,0,0,'confirmed'],
 ['automatic_preference','Автомат предпочтителен, но возможны исключения',.72,0,0,'confirmed'],
 ['lower_mileage','При прочих равных меньший пробег лучше',.82,0,0,'confirmed'],
 ['mainstream_year_2020','Простые массовые модели желательно рассматривать от 2020 года',.76,0,0,'confirmed'],
 ['interesting_year_2017','Mercedes и другие интересные варианты допустимы от 2017 года',.74,0,0,'confirmed'],
 ['flexible_exceptions','Мягкие предпочтения не являются жёсткими фильтрами',.95,0,0,'confirmed'],
 ['rear_seats_required','Обязателен полноценный задний ряд сидений',1,0,0,'confirmed'],
 ['exclude_commercial_vans','Исключить коммерческие фургоны и «пирожки»',1,0,0,'confirmed'],
 ['exclude_minibuses','Исключить микроавтобусы и пассажирско-грузовой транспорт',1,0,0,'confirmed']
].forEach(x=>seedHypothesis.run(...x,now));
db.prepare(`INSERT OR IGNORE INTO app_settings(key,value_json,updated_at) VALUES('required_vat_deductible','true',?)`).run(now);
db.prepare(`INSERT OR IGNORE INTO app_settings(key,value_json,updated_at) VALUES('hard_exclusions',?,?)`).run(JSON.stringify({commercialVans:true,minibuses:true,twoSeaters:true,rearSeatsRequired:true}),now);
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(data))};const body=async req=>{let s='';for await(const c of req)s+=c;return s?JSON.parse(s):{}};
const records=()=>db.prepare(`SELECT d.car_id carId,d.decision,d.created_at at,f.attribute_key,f.sentiment FROM car_decisions d LEFT JOIN attribute_feedback f ON f.car_id=d.car_id ORDER BY d.created_at`).all().reduce((a,r)=>{let x=a.find(v=>v.carId===r.carId);if(!x){x={carId:r.carId,decision:r.decision,at:Number(r.at),feedback:{}};a.push(x)}if(r.attribute_key)x.feedback[r.attribute_key]=r.sentiment;return a},[]);
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1');if(req.method==='GET'&&url.pathname==='/api/state'){const rs=records(),row=db.prepare(`SELECT value_json FROM app_settings WHERE key='feed_index'`).get();return json(res,200,{records:rs,index:row?JSON.parse(row.value_json):rs.length})}if(req.method==='POST'&&url.pathname==='/api/decisions'){const b=await body(req),now=Date.now();db.exec('BEGIN');try{db.prepare(`INSERT INTO car_decisions(car_id,decision,created_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(car_id) DO UPDATE SET decision=excluded.decision,updated_at=excluded.updated_at`).run(b.carId,b.decision,b.at||now,now);db.prepare('DELETE FROM attribute_feedback WHERE car_id=?').run(b.carId);const add=db.prepare(`INSERT INTO attribute_feedback(car_id,attribute_key,sentiment,created_at,updated_at) VALUES(?,?,?,?,?)`);for(const[k,v]of Object.entries(b.feedback||{}))add.run(b.carId,k,v,now,now);db.prepare(`INSERT INTO app_settings(key,value_json,updated_at) VALUES('feed_index',?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at`).run(JSON.stringify(b.index),now);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return json(res,200,{ok:true})}if(req.method==='POST'&&url.pathname==='/api/undo'){const b=await body(req);db.exec('BEGIN');try{db.prepare('DELETE FROM attribute_feedback WHERE car_id=?').run(b.carId);db.prepare('DELETE FROM car_decisions WHERE car_id=?').run(b.carId);db.prepare(`INSERT INTO app_settings(key,value_json,updated_at) VALUES('feed_index',?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at`).run(JSON.stringify(b.index),Date.now());db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return json(res,200,{ok:true})}if(req.method==='POST'&&url.pathname==='/api/reset'){db.exec('DELETE FROM attribute_feedback;DELETE FROM car_decisions;DELETE FROM app_settings;');return json(res,200,{ok:true})}json(res,404,{error:'Not found'})}catch(e){console.error(e);json(res,500,{error:'Database error'})}});server.listen(4318,'127.0.0.1',()=>console.log('eCars Scout API: http://127.0.0.1:4318'));
